# Generated by Django 3.2.18 on 2023-03-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20230309_2158'),
        ('events', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='eventgenre',
            unique_together={('event', 'genre')},
        ),
    ]
