# Generated by Django 3.2.18 on 2023-02-19 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Going',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posted_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goings', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'posted_event')},
            },
        ),
    ]
